### ISSUE TITLE
purescript-maps: Unexpected token

### ISSUE THREAD

**Issue by garyb** [Pauan/rollup-plugin-purs#6]
Due to `delete` https://github.com/purescript/purescript-maps/blob/c673935784492b5f181bdf392944d4c8245028a9/src/Data/StrMap/ST.purs#L10:
```
2: var peek = $foreign.peekImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
3: export { peek };
4: export { delete } from "./foreign";
            ^
5: export { new } from "./foreign";
6: export { poke } from "./foreign";
```

**Comment by Pauan** [comment]
This is a [known bug in acorn](https://github.com/ternjs/acorn/issues/490), which was fixed, so we just need to wait for acorn to publish a new version to npm.

**Comment by Pauan** [comment]
@garyb `acorn@4.0.8` has been released, please upgrade to the latest version of `rollup` and `rollup-plugin-purs` and then try again.

Note: you don't need to use `rollup-plugin-node-resolve` anymore, unless you want to bundle npm modules (from `node_modules`).

**Comment by garyb** [comment]
The problem persists. `acorn` doesn't seem to be present at all in `node_modules` though, so it seems a little odd if that was the problem?

**Comment by Pauan** [comment]
@garyb What's your version of `rollup` and `rollup-plugin-purs`? And does the problem still happen even after completely deleting `node_modules` and re-running `npm install`?

**Comment by garyb** [comment]
`rollup` 0.41.4, `rollup-plugin-purs` 1.0.16. And yes, I deleted `node_modules` and tried again when it didn't work the first time. I also spent a while removing anything from my global `node_modules` that could possibly be interfering, even though that shouldn't make a difference.

**Comment by Pauan** [comment]
@garyb Ahh, I see the problem. Rollup is deployed as a bundle, and so it bundles all of its dependencies (including `acorn`).

So even though the problem was fixed in `acorn`, Rollup needs to be re-bundled and re-published, so we now need to wait for Rollup to release a new version.

I'll leave this issue open until we've verified that it's fixed.

**Comment by garyb** [comment]
Here's a minimal example: https://github.com/garyb/purs-rollup-test.

**Comment by garyb** [comment]
Ah ok!

**Comment by Cmdv** [comment]
Just tried this out again today with latest version of rollup and still the same error :(

**Comment by Pauan** [comment]
Yeah, it seems that Rollup hasn't been updated yet. I pinged them, so hopefully it'll get fixed soon.

**Comment by Cmdv** [comment]
Thanks @Pauan

**Comment by Pauan** [comment]
@garyb @Cmdv Okay, it's been 26 days since Rollup was last updated, and it doesn't look like it's going to be fixed anytime soon.

So I put in a temporary hacky workaround which fixes this issue. Please upgrade to `1.0.37` and try again.

**Comment by Cmdv** [comment]
Cool thanks @Pauan will give it a try and report back 😄

**Comment by garyb** [comment]
Cool, the plugin _almost_ works for SlamData now 😆

**Comment by Pauan** [comment]
@garyb Bug reports welcome.

**Comment by garyb** [comment]
Sure, it's a problem in one of the non dependencies really (duplicate export), thought I'd look into that first.

**Comment by Pauan** [comment]
@garyb In that case I should be able to fix that pretty easily, I'll try to get a fix pushed out soon.
